#!/bin/bash

intern=LVDS-1
extern=HDMI-1
tema_notebook="$HOME/.config/rofi/themes/notebook.rasi"
tema_monitor="$HOME/.config/rofi/themes/lateral.rasi"

if xrandr | grep "$extern disconnected"; then
    rofi -theme "$tema_notebook" -lines 0 -show drun  -lines 8 -line-margin 4 -width 20 -padding 16

else
    rofi -theme "$tema_monitor" -lines 0 -show drun  -lines 8 -line-margin 4 -width 20 -padding 16
fi
